# Central BL
- platform: broadlink
  host: 192.168.0.61
  mac: '34:EA:34:F4:3A:5D'
  timeout: 15
  switches:
    c1a:
      friendly_name: "Maracujá"
      command_on: 'sjk0AA0jJAwNIyQMDSMkDA0jJAwNIyQMDSMkDA0jJAwNIyQMDSMkDA0jJAwNIyQMDSMkDA0AAWcAAAAA'
      command_off: 'sgk0AAwkDCQMJCMNDCQMJCMNDCQjDSMNJAwMJCQMDSMkDCQMDCQkDQwkDCQMJAwkIw0MIw0AAWcAAAAA'
    c1b:
      friendly_name: "Lateral"
      command_on: 'sgk0AAwkDCQMJCMNDCQMJAwkDCQjDSMNIw0jDSMNDCQMJAwkIw0MJCMNIw0jDSMNIw0jDQwAAWgAAAAA'
      command_off: 'sjk0AAwkDCQjDQwkDCQjDSMNDCQjDSMNDCQjDQwkIw0MJAwkIw0jDSMNDCQjDSMNIw0MJAwAAWcAAAAA'
    c2a:
      friendly_name: "Garagem"
      command_on: 'sgk0AAwkDCQMJCMNDCUMJCMNDCQjDQwkDCQjDQwkIw0MJCMNDCQjDSMNDCQMJAwkDCQjDQwAAWgAAAAA'
      command_off: 'sjk0AAwkIw0jDQwkIw0jDSMNIw0jDSMNDCQMJAwkIw0jDSMNIw0jDSMNDCQMJAwkDCQMJAwAAWgAAAAA'
    c2b:
      friendly_name: "Grama"
      command_on: 'si40AAwlDCUjDgwlIw0LJSMOIw0jDgwkDCQjDSMNIw0jDSMNIw0jDSMNIg0MJCMNIw0jDQsAAWgAAAAA'
      command_off: 'shc0AA0kJAwkDSQMDCQNJA0kJAwkDCQNJA0jDQwkDSQjDQwkDSMkDAwkDCQjDCQMJAwMIwwAAWcAAAAA'
    c3a:
      friendly_name: "TV"
      command_on: 'sgk0AAwkDCQjDSQNIw0MJAwkDCQkDSMNIw0kDSMNDCQMJAwkIw0jDCMNDSMMJCQMDCQkDAwAAWcAAAAA'
      command_off: 'sjI0AA0kDSQkDAwkJA0kDQwkDSQMJAwkDSQjDQwkJA0jDCMNDCQjDA0jJAwMJCQMIw0MJA0AAWcAAAAA'
    c3b:
      friendly_name: "Jantar"
      command_on: 'sgCGACALIwwjDAwjIwwjCyMMIwwjDCMMIgwjDCMLDAABZwwjDCMjDAwjIwwiDSMMIg0LIyMMIwwjDCMMIg0MIyIMIwwjDCMMIwsjDCMMIwsjDAwAAWYMJAsjIw0LIyMMIwwjDCMMDCMjDCMMIwwiDCMMDCMjDCMMIg0iDCMMIwsjDCMMIwwLAAXcAAA='
      command_off: 'sgk0AA0kDSQNJCQNDCQNJAwkDSQMIw0kJA0MJAwkJA0MIw0kJA0jDSQMJAwjDSMMDCQkDA0AAWcAAAAA'


#tomada
- platform: broadlink
  host: 192.168.0.63
  mac: '34:EA:34:F5:A0:E3'
  type:  sp3
  friendly_name: 'Tomada'
# casal
- platform: broadlink
  host: 192.168.0.65
  mac: 'B4:43:0D:F9:2D:48'
  timeout: 15
  switches:
    casal24:
      friendly_name: "Ar Casal 24ºC"
      command_on: 'JgCSAAABKZEXNRcQFxEWNhc0FxEXEBcRFhEYEBYSFjUWEhcQFhIWERcRFxAXERcRFhEXNRc0FzUWEhcQFhIWERc1FxEXNBcRFxAWNhcQFwACjhcRFhEXERYRFxEXEBcRFhEXNRc1FhEXERcQGBAXERcQFhIXEBcRFhEXERcRFxAWEhcQFhIXEBYSFjYWNRYSFjUXAA0FAAAAAAAA'
    casal18:
      friendly_name: "Ar Casal 18ºC"
      command_on: 'JgCSAAABKZIXNRYRFxEWNhc0FxEWERcRFhEXNRcRFhEWEhYRFxEWEhcQFhIWERYSFhEXNRY2FjUWEhYRFxEXEBc1FxEXNBcRFhEXNRYSFgACjhcRFhEXERYRFxEWEhYRFhIWNRc1FxEWERYSFhEXERYRFxEWERcRFhIWERYSFhEWEhYRFxEWERcRFjYWERY2FhEXAA0FAAAAAAAA'
    casal0:
      friendly_name: "Ar Casal Desligar"
      command_on: 'JgCSAAABKZIWNhYRFhIWERc1FhIWERYSFhEWEhYRFzUWEhYRFhIWERYSFxAXERYRFxEWNhYRFjYWERYSFhEXERY2FhEWNhYRFxEWNhYRFgACjBkRFxEWEhYRFhIWERYSFhEXNRY2FhEWEhcQFhIWERcRFhEXERYSFhEXERYRFxEWERcRFhIWERYSFjUXNRYSFhEWAA0FAAAAAAAA'

# Pedro
- platform: broadlink
  host: 192.168.0.66
  mac: 'B4:43:0D:F9:32:D7'
  timeout: 15
  switches:
    pedro24:
      friendly_name: "Ar Pedro 24ºC"
      command_on: 'JgCSAAABKZEXNRcQFxEWNhc0FxEXEBcRFhEYEBYSFjUWEhcQFhIWERcRFxAXERcRFhEXNRc0FzUWEhcQFhIWERc1FxEXNBcRFxAWNhcQFwACjhcRFhEXERYRFxEXEBcRFhEXNRc1FhEXERcQGBAXERcQFhIXEBcRFhEXERcRFxAWEhcQFhIXEBYSFjYWNRYSFjUXAA0FAAAAAAAA'
    pedro18:
      friendly_name: "Ar Pedro 18ºC"
      command_on: 'JgCSAAABKZIXNRYRFxEWNhc0FxEWERcRFhEXNRcRFhEWEhYRFxEWEhcQFhIWERYSFhEXNRY2FjUWEhYRFxEXEBc1FxEXNBcRFhEXNRYSFgACjhcRFhEXERYRFxEWEhYRFhIWNRc1FxEWERYSFhEXERYRFxEWERcRFhIWERYSFhEWEhYRFxEWERcRFjYWERY2FhEXAA0FAAAAAAAA'
    pedro0:
      friendly_name: "Ar Pedro Desligar"
      command_on: 'JgCSAAABKZIWNhYRFhIWERc1FhIWERYSFhEWEhYRFzUWEhYRFhIWERYSFxAXERYRFxEWNhYRFjYWERYSFhEXERY2FhEWNhYRFxEWNhYRFgACjBkRFxEWEhYRFhIWERYSFhEXNRY2FhEWEhcQFhIWERcRFhEXERYSFhEXERYRFxEWERcRFhIWERYSFjUXNRYSFhEWAA0FAAAAAAAA'

