alias: 'Fumaça Cozinha'
trigger:
  platform: state
  entity_id: sensor.status_gas
#  from: 'Puro'
  to: 'Fumaça'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home
      volume_level: "1"
  - service: tts.google_say
    data:
      entity_id: media_player.google_home
      language: pt
      message: 'Atenção! Alto nível de Fumaça ou gás detectados!'
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home
      volume_level: "0.5"
